### ISSUE TITLE
Catastrophic error

### ISSUE THREAD

**Issue by Feradose** [Darkhax-Minecraft/Stronger-Snowballs#1]
Snowballs are applying **invisibility** rather than the intended effect
Splash potions are applying the intended effect and **invisibility**

Removing the mod makes snowballs act as normal
I would upload the log to the pastebin but it's too large I am sorry
[latest.log](https://github.com/Darkhax-Minecraft/Stronger-Snowballs/files/4647816/latest.log)

**Comment by Darkhax** [comment]
This mod is extremely simple and there isn't really any room for a bug like this to happen. It's possible that another mod you are using is causing this to happen through some weird interaction. 

With the mod removed, does the splash potion still cause invisibility?

**Comment by Feradose** [comment]
You are right, there is a weird interaction that causes all effects to also apply invisibility, invisibility that isn't detected by any status reading methods

Removing your mod results in only the splash potions causing invisibility while snowballs act as usual, I apologize for the inconvenience
