### ISSUE TITLE
no configurable options

### ISSUE THREAD

**Issue by ElfKing94** [Darkhax-Minecraft/Stronger-Snowballs#3]
hi i cant configure anything with this mod nor does it damage nether mobs like its says. wonder if thats a bug? thanks

**Comment by ElfKing94** [comment]
the lack of damage to nether mobs was another conflicting mod but if this was configurable that would be wonderful. thanks

**Comment by Darkhax** [comment]
This mod is configurable, if you don't see the `strongersnowballs.json` file in your config folder then the mod is not installed properly. This config allows you to change how much damage the snowball does and change the slowness debuff applied to mobs. You can change the list of affected mobs by using the [`strongersnowballs:hurt_by_snow`](https://github.com/Darkhax-Minecraft/Stronger-Snowballs/blob/1.19.2/Common/src/main/resources/data/strongersnowballs/tags/entity_types/hurt_by_snow.json) entity tag.
